### ISSUE TITLE
Connect Netlify (or something similar) to github

### ISSUE THREAD

**Issue by stackoverfloweth** [stackoverfloweth/use-vue#1]
would be sweet to have the site automatically built and deployed to usevue.dev when main branch has merge

**Comment by space-age-pete** [comment]
How exactly was this handled for Prefect? Just some GitHub Action?

**Comment by stackoverfloweth** [comment]
> How exactly was this handled for Prefect? Just some GitHub Action?

Not sure if the trigger was on GitHub or the other way around. It could probably work either way.
